spring:
  application:
    name: grab-postgresql
  config:
    activate:
      on-profile: uat
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port: 3000
