apiVersion: batch/v1
kind: Job
metadata:
  name: grabcar-postgre-sql
  namespace: grab-car  # Set the namespace
spec:
  template:
    spec:
      containers:
        - name: grabcar-postgre-sql
          image: ervincode/grabcar-postgre-sql:${IMAGE_TAG} # Uses the same image with Liquibase inside
          imagePullPolicy: Always
          command: ["java", "-jar", "app.jar"]  # Runs migrations
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_PROFILES_ACTIVE
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
            - name: DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_DRIVER
            - name: LIQUIBASE_CHANGELOG_FILE
              value: "classpath:/db/changelog/db.changelog-master.xml"
#          volumeMounts:
#            - name: changelog-volume
#              mountPath: /app/resources/db/changelog
#      volumes:
#        - name: changelog-volume
#          emptyDir: {}
      restartPolicy: Never
